apiVersion: apps/v1
kind: Deployment
metadata:
  name: app42
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app42
  template:
    metadata:
      labels:
        app: app42
    spec:
      containers:
      - name: app42
        image: wil42/playground:v1
        ports:
        - containerPort: 8888
